# Generated by Django 5.1.1 on 2024-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
