# Generated by Django 5.1.1 on 2024-10-01 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_genre_item_platform_shoppingcart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
